<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="Keywords"  content="{$org.Org_Keywords},微厦科技" />
<meta name="Description" content="{$org.Org_Description},微厦科技" />
<!--核心Js文件-->
<script type="text/javascript" src="/Utility/CoreScripts/jquery.js"></script>
<script type="text/javascript" src="/Utility/CoreScripts/artTemplate.js"></script>
<script type="text/javascript" src="../CoreScripts/Extend.js"></script>
<script type="text/javascript" src="../CoreScripts/easydrag.js"></script>
<script type="text/javascript" src="../CoreScripts/PageBox.js"></script>
<script type="text/javascript" src="/Utility/CoreScripts/MessageBox.js"></script>
<script type="text/javascript" src="/Utility/CoreScripts/Verify.js"></script>
<!--核心Css文件-->
<link rel="stylesheet" type="text/css" href="/Utility/iconfont/iconfont.css"/>
<link rel="stylesheet" type="text/css" href="../CoreStyles/public.css"/>
<link rel="stylesheet" type="text/css" href="../CoreStyles/PageBox.css"/>
<link rel="stylesheet" type="text/css" href="/Utility/CoreStyles/MessageBox.css"/>
<link rel="stylesheet" type="text/css" href="/Utility/CoreStyles/Jme.css"/>
<!--公共的Js文件-->
<script type="text/javascript" src="../CoreScripts/public.js"></script>
<!--后面就是各个页面自己的了-->