<meta charset="utf-8"/>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1.0, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=yes" />
<meta name="format-detection" content="email=no" />
<script type="text/javascript" src="../Scripts/webdesk.ui.core.js"></script>
<style type="text/css">
    *[v-cloak]>* {
        display: none !important;
    }
    *[v-cloak]::before {
        content: "*";
        display: block;
        width:50px;
        height:50px;
        text-align: center;
        float:left;
        font-size: 50px;
        color:#999;
        animation: rotate_360 0.4s infinite linear;
    }
    *[v-cloak]::after {
        content: "...";
        display: inline;
        line-height:50px;   
        color:#999;    
    }
    @keyframes rotate_360 {
        0% {
            transform: rotate(0deg);
        }

        25% {
            transform: rotate(90deg);
        }

        50% {
            transform: rotate(180deg);
        }

        75% {
            transform: rotate(270deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }

</style>
<script>
    document.oncontextmenu=new Function("event.returnValue=false;");
    //document.onselectstart=new Function("event.returnValue=false;");
</script>