<meta charset="utf-8" />
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no"/>
<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1.0, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
<meta name="format-detection" content="telephone=yes" />
<meta name="format-detection" content="email=no" />
<meta name="Keywords"  content="{$org.Org_Keywords},微厦科技" />
<meta name="Description" content="{$org.Org_Description},微厦科技" />
<!--核心Js文件-->
<script type="text/javascript" src="/Utility/CoreScripts/jquery.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/vue.min.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/axios.min.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/Verify.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/artTemplate.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/Extend.js?ver={$version}"></script>
<script type="text/javascript" src="../scripts/loading.js?ver={$version}"></script>
<!--核心Css文件-->
<link rel="stylesheet" type="text/css" href="/Utility/iconfont/iconfont.css?ver={$version}"/>



