! function() {
    /* 以下信息,应该存储到单独的 js 文件或者数据库中. */
    /* 模块分类信息 */
    var sorts = [{
        id: 0,
        name: "ui",
        brief: "界面"

    }, {
        id: 1,
        name: "navMenu",
        brief: "导航菜单"
    }, {
        id: 2,
        name: "function",
        brief: "功能"
    }, {
        id: 3,
        name: "device",
        brief: "设备"
    }, {
        id: 4,
        name: "api",
        brief: "API对象"
    }, {
        id: 5,
        name: "other",
        brief: "开放SDK"
    }];

    /* 模块基础信息 */
    var modules = [{
            id: 0,
            name: "multiSelector",
            brief: "自定义数据源的多项选择器",
            sortId: 0,
            versionID: 0
        }, {
            id: 1,
            name: "shakeView",
            brief: "支持自定义摇一摇效果页",
            sortId: 0,
            versionID: 0
        }, {
            id: 2,
            name: "listContact",
            brief: "联系人列表，可自定义联系人数据源",
            sortId: 0,
            versionID: 0
        }, {
            id: 3,
            name: "citySelector",
            brief: "选择器的形式弹出全国个地区城市列表",
            sortId: 0,
            versionID: 0
        }, {
            id: 4,
            name: "graph",
            brief: "贝塞尔曲线，点击结点可返回事件",
            sortId: 0,
            versionID: 0
        }, {
            id: 5,
            name: "scrollPicture",
            brief: "图片自动滚动联播，支持http协议，本地缓存功能",
            sortId: 0,
            versionID: 0
        }, {
            id: 6,
            name: "searchBar",
            brief: "可自定义的搜索界面",
            sortId: 0,
            versionID: 0
        }, {
            id: 7,
            name: "timeSelector",
            brief: "上下滚轮效果的时间选择器",
            sortId: 0,
            versionID: 0
        }, {
            id: 8,
            name: "periodSelector",
            brief: "上下滚轮效果的时段选择器",
            sortId: 0,
            versionID: 0
        }, {
            id: 9,
            name: "arcProgress",
            brief: "圆形、扇形、月牙形进度条",
            sortId: 0,
            versionID: 0
        }, {
            id: 10,
            name: "barChart",
            brief: "可以点击查看数据的柱状图",
            sortId: 0,
            versionID: 0
        }, {
            id: 11,
            name: "calendar",
            brief: "特殊日期标记、查看日历模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 12,
            name: "cityList",
            brief: "可自定义数据源的城市列表",
            sortId: 0,
            versionID: 0
        }, {
            id: 13,
            name: "lineChart",
            brief: "折线图表，支持显示多条k线",
            sortId: 0,
            versionID: 0
        }, {
            id: 14,
            name: "listView",
            brief: "可配置item侧滑方式的文件列表",
            sortId: 0,
            versionID: 0
        }, {
            id: 15,
            name: "coverFlow",
            brief: "将多个封面以3D界面形式展示(立体倒影效果)",
            sortId: 0,
            versionID: 0
        }, {
            id: 16,
            name: "panorama",
            brief: "球状体全景图片展示",
            sortId: 0,
            versionID: 0
        }, {
            id: 17,
            name: "personalCenter",
            brief: "个人中心用户信息样式",
            sortId: 0,
            versionID: 0
        }, {
            id: 18,
            name: "pieChart",
            brief: "可随手势旋转的饼形图",
            sortId: 0,
            versionID: 0
        }, {
            id: 19,
            name: "slider",
            brief: "可以显示数值气泡的滑杆，可自定义大小值、设置当前值",
            sortId: 0,
            versionID: 0
        }, {
            id: 20,
            name: "aliPay",
            brief: "支付宝支付",
            sortId: 5,
            versionID: 0
        }, {
            id: 21,
            name: "baiduLocation",
            brief: "百度定位功能",
            sortId: 5,
            versionID: 0
        }, {
            id: 22,
            name: "baiduMap",
            brief: "百度地图模块,封装了百度地图的sdk",
            sortId: 5,
            versionID: 0
        }, {
            id: 23,
            name: "qq",
            brief: "QQ授权登录及分享内容到QQ",
            sortId: 5,
            versionID: 0
        }, {
            id: 24,
            name: "sinaWeiBo",
            brief: "新浪微博授权登录及分享内容到微博",
            sortId: 5,
            versionID: 0
        }, {
            id: 25,
            name: "weiXin",
            brief: "微信分享接口，微信支付",
            sortId: 5,
            versionID: 0
        }, {
            id: 26,
            name: "touchID",
            brief: "iPhone指纹身份验证",
            sortId: 3,
            versionID: 3
        }, {
            id: 27,
            name: "bluetooth",
            brief: "通过蓝牙传输文字串，文件，图片等数据",
            sortId: 3,
            versionID: 0
        }, {
            id: 28,
            name: "trans",
            brief: "把xml文件解析成json",
            sortId: 2,
            versionID: 0
        }, {
            id: 29,
            name: "installApp",
            brief: "安装应用",
            sortId: 4,
            versionID: 0
        }, {
            id: 30,
            name: "statusBar",
            brief: "是否全屏及IOS的状态栏样式设置",
            sortId: 4,
            versionID: 0
        }, {
            id: 31,
            name: "miscellaneous",
            brief: "打开通讯录、清除缓存、提示框、选择器等",
            sortId: 4,
            versionID: 0
        }, {
            id: 32,
            name: "download",
            brief: "下载功能，支持显示进度、断点续传等",
            sortId: 4,
            versionID: 0
        }, {
            id: 33,
            name: "openApp",
            brief: "打开其他应用",
            sortId: 4,
            versionID: 0
        }, {
            id: 34,
            name: "sensor",
            brief: "监听传感器信息",
            sortId: 4,
            versionID: 0
        }, {
            id: 35,
            name: "geo",
            brief: "获取位置信息(Android需连接google服务器)",
            sortId: 4,
            versionID: 0
        }, {
            id: 36,
            name: "filesystem",
            brief: "文件系统",
            sortId: 4,
            versionID: 0
        }, {
            id: 37,
            name: "mail",
            brief: "发送邮件功能，支持附件",
            sortId: 4,
            versionID: 0
        }, {
            id: 38,
            name: "tel",
            brief: "拨打电话及发送短信功能",
            sortId: 4,
            versionID: 0
        }, {
            id: 39,
            name: "ajax",
            brief: "跨域异步请求",
            sortId: 4,
            versionID: 0
        }, {
            id: 40,
            name: "getPicture",
            brief: "从系统相册、相机获取图片",
            sortId: 4,
            versionID: 0
        }, {
            id: 41,
            name: "setPrefs",
            brief: "设置偏好数据",
            sortId: 4,
            versionID: 0
        }, {
            id: 42,
            name: "event",
            brief: "事件监听，如网络、电量、操作等",
            sortId: 4,
            versionID: 0
        }, {
            id: 43,
            name: "widget",
            brief: "在app中运行一个widget项目",
            sortId: 4,
            versionID: 0
        }, {
            id: 44,
            name: "sysInfo",
            brief: "获取设备系统信息",
            sortId: 4,
            versionID: 0
        }, {
            id: 45,
            name: "contact",
            brief: "对联系人进行增删查改等操作的功能",
            sortId: 3,
            versionID: 0
        }, {
            id: 46,
            name: "db",
            brief: "数据库操作对象",
            sortId: 2,
            versionID: 0
        }, {
            id: 47,
            name: "downloadManager",
            brief: "下载管理功能",
            sortId: 2,
            versionID: 0
        }, {
            id: 48,
            name: "fileBrowser",
            brief: "本地文件浏览，可返回文件路径",
            sortId: 2,
            versionID: 0
        }, {
            id: 49,
            name: "fs",
            brief: "文件系统，可创建、删除、复制、移动、修改等",
            sortId: 2,
            versionID: 0
        }, {
            id: 50,
            name: "imageBrowser",
            brief: "具有相册效果的本地图片查看器",
            sortId: 2,
            versionID: 0
        }, {
            id: 51,
            name: "scanner",
            brief: "二维码扫描器，支持生成条码/二维码",
            sortId: 2,
            versionID: 0
        }, {
            id: 52,
            name: "zip",
            brief: "压缩及解压缩功能支持压缩多个文件",
            sortId: 2,
            versionID: 0
        }, {
            id: 53,
            name: "cardReader",
            brief: "卡片阅读功能",
            sortId: 2,
            versionID: 0
        }, {
            id: 54,
            name: "stackMenu",
            brief: "stack 菜单",
            sortId: 1,
            versionID: 0
        }, {
            id: 55,
            name: "scrollRotation",
            brief: "图片旋转滚动联播器",
            sortId: 1,
            versionID: 0
        }, {
            id: 56,
            name: "circularMenu",
            brief: "转盘菜单，可自定义按钮",
            sortId: 1,
            versionID: 0
        }, {
            id: 57,
            name: "tabBarMenu",
            brief: "底部导航菜单",
            sortId: 1,
            versionID: 0
        }, {
            id: 58,
            name: "chatBox",
            brief: "聊天表情输入框，可自定义表情集，选择相册事件",
            sortId: 0,
            versionID: 0
        }, {
            id: 59,
            name: "loadingLabel",
            brief: "加载标签，顶部栏加载效果，可开启暂停",
            sortId: 0,
            versionID: 0
        }, {
            id: 60,
            name: "bubbleMenu",
            brief: "气泡菜单，浮动菜单多用于内容操作的功能",
            sortId: 1,
            versionID: 0
        }, {
            id: 61,
            name: "sideMenu",
            brief: "边框菜单，屏幕左右俩侧弹动菜单",
            sortId: 1,
            versionID: 0
        }, {
            id: 62,
            name: "pullMenu",
            brief: "可随手指拖动上下拉动的菜单，可自定义按钮",
            sortId: 1,
            versionID: 0
        }, {
            id: 63,
            name: "navigationMenu",
            brief: "导航条按钮，可显示隐藏",
            sortId: 1,
            versionID: 0
        }, {
            id: 64,
            name: "actionButton",
            brief: "多屏按钮功能，支持滑动切换",
            sortId: 1,
            versionID: 0
        }, {
            id: 65,
            name: "arcMenu",
            brief: "动画菜单，可自定义子菜单的位置",
            sortId: 1,
            versionID: 0
        }, {
            id: 66,
            name: "inputField",
            brief: "文字输入框",
            sortId: 0,
            versionID: 0
        }, {
            id: 67,
            name: "tabBar",
            brief: "支持滑动的底部标签栏",
            sortId: 1,
            versionID: 0
        }, {
            id: 68,
            name: "toast",
            brief: "自动消失的提示框",
            sortId: 4,
            versionID: 0
        }, {
            id: 69,
            name: "progress",
            brief: "进度提示，可设置动画类型",
            sortId: 4,
            versionID: 0
        }, {
            id: 70,
            name: "dialog",
            brief: "多种弹出对话框样式",
            sortId: 4,
            versionID: 0
        }, {
            id: 71,
            name: "pullToRefresh",
            brief: "下拉刷新功能",
            sortId: 4,
            versionID: 0
        }, {
            id: 72,
            name: "frameGroup",
            brief: "打开窗口组功能",
            sortId: 4,
            versionID: 0
        }, {
            id: 73,
            name: "frameAnimation",
            brief: "子窗口动画，平移、缩放、旋转等",
            sortId: 4,
            versionID: 0
        }, {
            id: 74,
            name: "frame",
            brief: "打开子窗口功能",
            sortId: 4,
            versionID: 0
        }, {
            id: 75,
            name: "slidLayout",
            brief: "侧滑显示动画效果，支持左右方向",
            sortId: 4,
            versionID: 0
        }, {
            id: 76,
            name: "multiWin",
            brief: "多窗口功能演示",
            sortId: 4,
            versionID: 0
        },
        //        {
        //            id: 78,
        //            name: "animation",
        //            brief: "打开窗口时动画效果",
        //            sortId: 4,
        //            versionID: 0
        //        },
        {
            id: 79,
            name: "netAudio",
            brief: "网络音频播放器，支持网络音频播放",
            sortId: 2,
            versionID: 0
        }, {
            id: 80,
            name: "speechRecognizer",
            brief: "语音识别功能，支持朗读",
            sortId: 5,
            versionID: 0
        }, {
            id: 81,
            name: "medias",
            brief: "音频录制及播放及本地视频和网络视频的播放",
            sortId: 4,
            versionID: 0
        }, {
            id: 82,
            name: "bookReader",
            brief: "具有翻页效果的文本阅读器",
            sortId: 2,
            versionID: 0
        }, {
            id: 83,
            name: "navigationBar",
            brief: "可自定义排版、拖动的标题导航条",
            sortId: 1,
            versionID: 0
        }, {
            id: 84,
            name: "pdfReader",
            brief: "PDF阅读器",
            sortId: 2,
            versionID: 0
        }, {
            id: 85,
            name: "docReader",
            brief: "文档阅读器，Android需第三方软件支持",
            sortId: 2,
            versionID: 0
        }, {
            id: 86,
            name: "meChat",
            brief: "实现手机用户与企业保持随时随刻沟通的客服工具",
            sortId: 5,
            versionID: 0
        }, {
            id: 87,
            name: "adsKuGuo",
            brief: "封装了酷果广告平台的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 88,
            name: "adsMogo",
            brief: "封装了芒果广告平台的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 88,
            name: "adsDomob",
            brief: "封装了多盟广告平台的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 89,
            name: "pushGeTui",
            brief: "推送模块，封装了个推的sdk",
            sortId: 5,
            versionID: 0
        }, {
            id: 90,
            name: "yzChannel",
            brief: "封装了游族游戏平台的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 91,
            name: "baiXing",
            brief: "封装了百姓网移动端的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 92,
            name: "tulingapi",
            brief: "封装了图灵机器人的SDK ",
            sortId: 5,
            versionID: 0
        }, {
            id: 93,
            name: "tencentPush",
            brief: "封装了腾讯信鸽的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 94,
            name: "slipList",
            brief: "可定制型更强的列表控件",
            sortId: 0,
            versionID: 0
        },
        //        {
        //            id: 95,
        //            name: "maketionCardReader",
        //            brief: "封装了脉可寻名片识别的sdk",
        //            sortId: 5,
        //            versionID: 0
        //        },
        {
            id: 96,
            name: "rongCloud",
            brief: "封装融云即时通讯的sdk",
            sortId: 5,
            versionID: 0
        }, {
            id: 97,
            name: "pingpp",
            brief: "ping++多渠道支付接口",
            sortId: 5,
            versionID: 0
        }, {
            id: 98,
            name: "baiduNavigation",
            brief: "封装了百度导航的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 99,
            name: "socketManager",
            brief: "封装了 socket 的相关操作",
            sortId: 2,
            versionID: 0
        }, {
            id: 100,
            name: "ajpush",
            brief: "封装了 极光推送平台 的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 100,
            name: "uscSpeechRecognizer",
            brief: "云知声语音识别SDK.",
            sortId: 5,
            versionID: 0
        }, {
            id: 101,
            name: "brightBeacon",
            brief: "与iBeacon设备互动的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 102,
            name: "ipaynow",
            brief: "封装了众多主流支付方式的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 103,
            name: "yzxVerification",
            brief: "封装了云之讯开放平台的智能验证SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 104,
            name: "ksisdk",
            brief: "提供电子数据的签名和验证服务的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 105,
            name: "clipboard",
            brief: "剪切板",
            sortId: 2,
            versionID: 0
        }, {
            id: 106,
            name: "mediaScanner",
            brief: "图片多项选择器",
            sortId: 3,
            versionID: 0
        }, {
            id: 107,
            name: "screenClip",
            brief: "屏幕截屏",
            sortId: 2,
            versionID: 0
        }, {
            id: 108,
            name: "imageFilter",
            brief: "图片滤镜",
            sortId: 2,
            versionID: 0
        }, {
            id: 109,
            name: "arcColorPicker",
            brief: "可自定义样式、内容颜色的环形取色器",
            sortId: 2,
            versionID: 0
        }, {
            id: 110,
            name: "button",
            brief: "可自定义的按钮",
            sortId: 0,
            versionID: 0
        }, {
            id: 111,
            name: "audio",
            brief: "音频播放器，支持本地和网络音频播放",
            sortId: 2,
            versionID: 0
        }, {
            id: 112,
            name: "jd",
            brief: "封装了京东授权登录SDK",
            sortId: 5,
            versionID: 0
        },

        {
            id: 113,
            name: "imageClip",
            brief: "封装了图片剪裁的接口，开发者可自定义裁剪界面",
            sortId: 2,
            versionID: 0
        }, {
            id: 114,
            name: "UIScrollPicture",
            brief: "UIScrollPicture 是一个图片轮播模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 115,
            name: "UIMediaScanner",
            brief: "UIMediaScanner是一个多媒体扫描器，可扫描系统的图片、视频等多媒体资源。",
            sortId: 0,
            versionID: 0
        }, {
            id: 116,
            name: "wx",
            brief: "wx 封装了微信开放平台的SDK，集成了微信登录、微信分享功能",
            sortId: 5,
            versionID: 0
        }, {
            id: 117,
            name: "UISearchBar",
            brief: "UISearchBar 是一个独立的搜索页面，可以返回搜索文本，监听录音按钮事件，保存、清除搜索记录。",
            sortId: 0,
            versionID: 0
        }, {
            id: 118,
            name: "UIChatBox",
            brief: "UIChatBox 模块是一个集成表情的聊天输入框。",
            sortId: 0,
            versionID: 0
        }, {
            id: 119,
            name: "UICustomPicker",
            brief: "UICustomPicker 模块模块是一个自定义内容选择器。",
            sortId: 0,
            versionID: 0
        }, {
            id: 120,
            name: "UICityList",
            brief: "UICityList 模块是一个可定制数据源的城市列表。",
            sortId: 0,
            versionID: 0
        }, {
            id: 121,
            name: "contacts",
            brief: "contacts 模块封装了系统通讯录的相关接口。",
            sortId: 3,
            versionID: 0
        }, {
            id: 122,
            name: "UICalendar",
            brief: "UICalendar 是一个日历选择模块。",
            sortId: 0,
            versionID: 0
        },

        {
            id: 123,
            name: "UIListView",
            brief: "UIListView 封装了一个数据列表控件，列表项水平侧滑可出现控制按钮",
            sortId: 0,
            versionID: 0
        }, {
            id: 124,
            name: "FNScanner",
            brief: "FNScanner 模块是一个二维码/条形码扫描器",
            sortId: 2,
            versionID: 0
        },

        {
            id: 125,
            name: "weibo",
            brief: "weibo 封装了新浪微博开放平台的 SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 126,
            name: "unionPay",
            brief: "unionPay 封装了银联支付的SDK",
            sortId: 5,
            versionID: 0
        }, {
            id: 127,
            name: "UIInput",
            brief: "UIInput 是一个输入框模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 128,
            name: "UIGraph",
            brief: "UIGraph 是一个贝塞尔曲线模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 129,
            name: "MNStack",
            brief: "MNStack 是一个栈菜单",
            sortId: 0,
            versionID: 0
        }, {
            id: 130,
            name: "UISelector",
            brief: "UISelector 是自定义分级联动选择器模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 131,
            name: "UILinkedPicker",
            brief: "UILinkedPicker 是自定义分级联动选择器模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 132,
            name: "shareAction",
            brief: "shareAction 是一个调用系统分享功能的模块",
            sortId: 2,
            versionID: 0
        }, {
            id: 133,
            name: "UIBarChart",
            brief: "UIBarChart 是一个柱状图模块",
            sortId: 0,
            versionID: 0
        }, {
            id: 134,
            name: "audioCover",
            brief: "audioCover 封装了设置音乐播放锁屏界面的相关接口",
            sortId: 0,
            versionID: 0
        }


    ];

    /* 版本信息. */
    var versions = [{
        id: 0,
        number: "1.0.0"
    }];

    /* 记录更新的信息. */
    var update = [];

    /* 记录bug 信息. */
    var bug = [];

    // ---------------------------------------------------

    window.dataSource = {
        sorts: sorts,
        modules: modules,
        versions: versions,
        update: update,
        bug: bug
    };
}()
