//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由一个工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Song.Site.Manage.Common
{

    public partial class Memo
    {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
