<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="Keywords"  content="{$org.Org_Keywords}" />
<meta name="Description" content="{$org.Org_Description}" />
<!--核心Js文件-->
<script type="text/javascript" src="/Utility/CoreScripts/jquery.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/Verify.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/Extend.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/MessageBox.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/easydrag.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/PageBox.js?ver={$version}"></script>

<!--核心Css文件-->
<link rel="stylesheet" type="text/css" href="../CoreStyles/public.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/CoreStyles/MessageBox.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/CoreStyles/PageBox.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/iconfont/iconfont.css?ver={$version}"/>
<!--公共的Js文件-->
<script type="text/javascript" src="../CoreScripts/public.js?ver={$version}"></script>
<script type="text/javascript" src="../CoreScripts/loading.js?ver={$version}"></script>
<!--后面就是各个页面自己的了-->