<script type="text/javascript" src="/Utility/CoreScripts/vue_min.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/polyfill.min.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/axios_min.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/api.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/jquery.js?ver={$version}"></script>
<script type="text/javascript" src="/Utility/CoreScripts/PageBox.js?ver={$version}"></script>

<script type="text/javascript" src="/Utility/ElementUi/index.js?ver={$version}"></script>



<!--核心Css文件-->
<link rel="stylesheet" type="text/css" href="../CoreStyles/public.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/CoreStyles/MessageBox.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/CoreStyles/PageBox.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/iconfont/iconfont.css?ver={$version}"/>
<link rel="stylesheet" type="text/css" href="/Utility/ElementUi/index.css?ver={$version}"/>