<meta charset="utf-8"/>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1.0, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=yes" />
<meta name="format-detection" content="email=no" />
<script type="text/javascript" src="/Utilities/Scripts/webdom.js"></script>
<script type="text/javascript" src="../Scripts/Public.js"></script>
<style type="text/css">
    *[v-cloak]>* {
        display: none !important;
    }
    *[v-cloak]::before {
        content: "/";
        display: block;
        width:24px;
        height:24px;
        text-align: center;
        float:left;
        font-size: 16px;
        color:#999;
        transform-origin: center center;
        animation: rotate_360 0.5s infinite linear;
    }
    *[v-cloak]::after {
        content: "loading ... ";
        display: inline;
        font-size: 13px;
        margin-left:10px;
        line-height:30px;
        color:#999;       
    }
    @keyframes rotate_360 {
        0% {
            transform: rotate(0deg);
        }

        25% {
            transform: rotate(90deg);
        }

        50% {
            transform: rotate(180deg);
        }

        75% {
            transform: rotate(270deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }

</style>